### ISSUE TITLE
support RxSwift 2.3.1

### ISSUE THREAD

**Issue by idanhaviv** [ivanbruel/Moya-ObjectMapper#9]
Hi,

working with XCode 7.3 requires RxSwift 2.3.1 for an compilation error regarding XCTests
but ObjectMapper requires RxSwift 2.2 on the pod file 

can you please update the requirements?

Best,

Idan
